import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 5
padding.y = 0

decorations = "Buttonless"

opacity = 0.8
blur = true

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 16
